### ISSUE TITLE
javascriptみて生成されたinputタグ

### ISSUE THREAD

**Issue by maesonger** [msng/jQuery.iPreview#1]
自分のような素人でも便利に使えるので、すごいです。

ただマニアックですが、
<td>で囲まれていて、insertcellを使って追加した、input（file属性）タグには
プレビューは効かないみたいでした。

追加した『input type = "file"』の下にも、画像表示されると、もっと便利じゃないかと思いました。

**Comment by msng** [comment]
後から挿入された `input` タグで使う場合は、挿入後に

``` javascript
$('その要素のセレクタ').iPreview();
```

を再度呼んでみてください。
